spring.application.name=Bancosol

spring.application.version=0.0.1-SNAPSHOT
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

# Configuración de codificación UTF-8
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
spring.messages.encoding=UTF-8

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bancosol_campanas
spring.datasource.username=admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
