CREATE TABLE "rol" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar UNIQUE NOT NULL
);

CREATE TABLE "usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "apellidos" varchar,
  "contrasena" varchar NOT NULL,
  "usuario" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "telefono" varchar,
  "area_asignada" varchar,
  "id_rol" integer NOT NULL
);

CREATE TABLE "cadena" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar UNIQUE NOT NULL,
  "codigo" varchar UNIQUE NOT NULL
);

CREATE TABLE "tienda" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar,
  "localidad" varchar,
  "domicilio" text,
  "c_postal" varchar,
  "zona_geografica" varchar,
  "id_cadena" integer NOT NULL,
  "id_capitan" integer
);

CREATE TABLE "notificacion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario_destino" integer NOT NULL,
  "fecha_creacion" timestamp,
  "mensaje" text NOT NULL
);

CREATE TABLE "campana" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "ano" integer NOT NULL,
  "dia_comienzo" date NOT NULL,
  "dia_final" date NOT NULL
);

CREATE TABLE "voluntario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_entidad" varchar NOT NULL,
  "persona_fisica" boolean DEFAULT true,
  "domicilio" text,
  "localidad" varchar,
  "codigo_postal" varchar,
  "n_voluntarios" integer DEFAULT 1,
  "observaciones" text
);

CREATE TABLE "turno" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo_turno" varchar,
  "hora_inicio" time NOT NULL,
  "hora_fin" time NOT NULL,
  "id_campana" integer NOT NULL,
  "id_voluntario" integer NOT NULL,
  "id_tienda" integer NOT NULL
);

CREATE TABLE "participa" (
  "id_campana" integer,
  "id_tienda" integer,
  "id_coordinador" integer,
  PRIMARY KEY ("id_campana", "id_tienda")
);

COMMENT ON TABLE "campana" IS 'Las fechas de inicio deben ser anteriores a las de fin. Las campañas no se pueden superponer en el tiempo.';

ALTER TABLE "usuario" ADD FOREIGN KEY ("id_rol") REFERENCES "rol" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tienda" ADD FOREIGN KEY ("id_cadena") REFERENCES "cadena" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tienda" ADD FOREIGN KEY ("id_capitan") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notificacion" ADD FOREIGN KEY ("id_usuario_destino") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "turno" ADD FOREIGN KEY ("id_campana") REFERENCES "campana" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "turno" ADD FOREIGN KEY ("id_voluntario") REFERENCES "voluntario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "turno" ADD FOREIGN KEY ("id_tienda") REFERENCES "tienda" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participa" ADD FOREIGN KEY ("id_campana") REFERENCES "campana" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participa" ADD FOREIGN KEY ("id_tienda") REFERENCES "tienda" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participa" ADD FOREIGN KEY ("id_coordinador") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;
