CREATE TABLE "rol" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar UNIQUE NOT NULL
);

CREATE TABLE "usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "apellidos" varchar,
  "contrasena" varchar NOT NULL,
  "usuario" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "telefono" varchar,
  "area_asignada" varchar,
  "id_rol" integer NOT NULL
);

CREATE TABLE "cadena" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar UNIQUE NOT NULL,
  "codigo" varchar UNIQUE NOT NULL
);

CREATE TABLE "tienda" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar,
  "localidad" varchar,
  "domicilio" text,
  "c_postal" varchar,
  "zona_geografica" varchar,
  "id_cadena" integer NOT NULL,
  "id_capitan" integer,
  "id_responsable_tienda" integer
);

CREATE TABLE "notificacion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario_destino" integer NOT NULL,
  "fecha_creacion" timestamp,
  "asunto" text NOT NULL,
  "mensaje" text NOT NULL
);

CREATE TABLE "campana" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "ano" integer NOT NULL,
  "dia_comienzo" date NOT NULL,
  "dia_final" date NOT NULL
);

CREATE TABLE "voluntario_base" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "domicilio" text,
  "zona_geografica" varchar,
  "codigo_postal" varchar,
  "aprobado" boolean DEFAULT false
);

CREATE TABLE "voluntario_fisico" (
  "id_voluntario" integer PRIMARY KEY,
  "nombre" text,
  "apellidos" text
);

CREATE TABLE "voluntario_entidad" (
  "id_voluntario" integer PRIMARY KEY,
  "nombre_asociacion" text,
  "n_voluntarios" integer,
  "id_responsable_entidad" integer
);

CREATE TABLE "turno" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo_turno" text NOT NULL,
  "dia" date,
  "hora_inicio" time NOT NULL,
  "hora_fin" time NOT NULL,
  "id_campana" integer NOT NULL,
  "id_voluntario" integer NOT NULL,
  "id_tienda" integer NOT NULL
);

CREATE TABLE "participa" (
  "id_campana" integer,
  "id_tienda" integer,
  "id_coordinador" integer,
  PRIMARY KEY ("id_campana", "id_tienda")
);

COMMENT ON TABLE "campana" IS 'Las fechas de inicio deben ser anteriores a las de fin. Las campañas no se pueden superponer en el tiempo.';

ALTER TABLE "usuario" ADD FOREIGN KEY ("id_rol") REFERENCES "rol" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tienda" ADD FOREIGN KEY ("id_cadena") REFERENCES "cadena" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tienda" ADD FOREIGN KEY ("id_capitan") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tienda" ADD FOREIGN KEY ("id_responsable_tienda") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notificacion" ADD FOREIGN KEY ("id_usuario_destino") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "voluntario_fisico" ADD FOREIGN KEY ("id_voluntario") REFERENCES "voluntario_base" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "voluntario_entidad" ADD FOREIGN KEY ("id_voluntario") REFERENCES "voluntario_base" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "voluntario_entidad" ADD FOREIGN KEY ("id_responsable_entidad") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "turno" ADD FOREIGN KEY ("id_campana") REFERENCES "campana" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "turno" ADD FOREIGN KEY ("id_voluntario") REFERENCES "voluntario_base" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "turno" ADD FOREIGN KEY ("id_tienda") REFERENCES "tienda" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participa" ADD FOREIGN KEY ("id_campana") REFERENCES "campana" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participa" ADD FOREIGN KEY ("id_tienda") REFERENCES "tienda" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participa" ADD FOREIGN KEY ("id_coordinador") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

INSERT INTO "rol" ("nombre") VALUES ('Administrador');          -- ID 1
INSERT INTO "rol" ("nombre") VALUES ('Coordinador');           -- ID 2
INSERT INTO "rol" ("nombre") VALUES ('Capitan');               -- ID 3
INSERT INTO "rol" ("nombre") VALUES ('Responsable Entidad');   -- ID 4
INSERT INTO "rol" ("nombre") VALUES ('Responsable Tienda');    -- ID 5

INSERT INTO "usuario" ("nombre", "apellidos", "contrasena", "usuario", "email", "telefono", "area_asignada", "id_rol")
VALUES ('Juan', 'Pérez García', 'admin123', 'jperez', 'juan.perez@email.com', '600111222', 'Málaga', 1);
